apiVersion: rbac.authorization.k8s.io/v1 #for v1.8.0++
#apiVersion: rbac.authorization.k8s.io/v1beta1 #for v1.7.x
kind: RoleBinding
metadata:
  name: ingress-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress
subjects:
  - kind: ServiceAccount
    name: default