apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.TodoAPI.ServiceName }}
spec:
  ports:
  - port: {{ .Values.TodoAPI.ServicePort }}
  selector:
    app: {{ .Values.TodoAPI.Name }}
    tier: backend
    environment: {{.Values.Global.Environment}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.TodoAPI.Name }}
spec:
  replicas:  {{.Values.TodoAPI.Replicas}}
  selector:
    matchLabels:
      app: {{ .Values.TodoAPI.Name }}
      tier: backend
      environment: {{.Values.Global.Environment}}
  minReadySeconds: 3
  template:
    metadata:
      labels:
        app: {{ .Values.TodoAPI.Name }}
        tier: backend
        environment: {{.Values.Global.Environment}}
    spec:
      containers:
        - name: {{.Values.TodoAPI.Name}}
          image: {{.Values.TodoAPI.Image}}:{{.Values.TodoAPI.ImageTag}}
          ports:
            - containerPort: {{.Values.TodoAPI.ContainerPort}}
          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.TodoAPI.ConfigName}}
                  key: db_url
            - name: IS_TEST_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.TodoAPI.ConfigName}}
                  key: is_test_mode
            - name: SPRING_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.TodoAPI.ConfigName}}
                  key: spring_log_level
            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.TodoAPI.ConfigName}}
                  key: app_log_level
            - name: USER_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.TodoAPI.ConfigName}}
                  key: user_api_url
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.TodoAPI.ConfigName}}
                  key: allowed_origins
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.Global.SecretName}}
                  key: azure_client_secret
            - name: AZURE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Values.Global.SecretName}}
                  key: azure_app_id
            - name: AD_IDENTITY_META_DATA_URL
              valueFrom:
                secretKeyRef:
                  name: {{.Values.Global.SecretName}}
                  key: ad_identity_meta_data
      #imagePullSecrets:
      #  - name: techdemosecret
